# LAB 6

In [ ]:
import torch

# Get the current device
torch.cuda.current_device

# Get the name of the GPU at device 0
torch.cuda.get_device_name(0)

# Trả về mức sử dụng bộ nhớ GPU hiện tại theo tensors (tính bằng byte) cho thiết bị
torch.cuda.memory_allocated()

# Trả về mức sử dụng bộ nhớ GPU hiện tại được quản lý bởi bộ phân bố bộ nhớ (tính theo byte)
torch.cuda.memory_reserved()


0

## Dataset with pythod

In [2]:
import torch
import numpy as np
import pandas as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("/Users/macbook/Desktop/Hoc tap/Số hoá/LAB 6/Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [12]:
df.shape

(150, 6)

In [13]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(["Species"], axis = 1).values
y = le.fit_transform(df["Species"].values)

# chia dữ liệu với test size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1, 1)
y_test = torch.LongTensor(y_test).reshape(-1, 1)

print(f"train size {len(y_train)}")

train size 120


In [14]:
labels, counts = y_train.unique( return_counts=True)
labels, counts

(tensor([0, 1, 2]), tensor([40, 41, 39]))

In [15]:
# tính đạo hàm bằng pytorch
# cho y = 2x^4  + x^3 + 3x^2 + 5X +1
# tính y'

# tạo một tensor với requirments_grad được đặt thành true
X = torch.tensor(2.0, requires_grad=True)
print(X)
print(X.grad)

# Định nghĩa hàm
y = 2*X**4 + X**3 + 3*X**2 + 5*X + 1
print(y)

# thực hiện truyền ngược và tính toán các gradient
y.backward()

# Kết quả đạo hàm
X.grad

tensor(2., requires_grad=True)
None
tensor(63., grad_fn=<AddBackward0>)


tensor(93.)

In [18]:
#BT
# Cho y = 5x^6 + 3x^3 + 2x^1 + x + 2x + 5x^4 + 1
# Cho biết độ dốc của đa thực trên tại điểm nào
import sympy as sp

# Khai báo biến
x = sp.symbols('x')

# Định nghĩa hàm đa thức
y = 5*x**6 + 5*x**4 + 3*x**3 + 3*x + 1

# Tính đạo hàm
dy_dx = sp.diff(y, x)

# Hiển thị kết quả
def slope_at_point(a):
    return dy_dx.subs(x, a)

# Ví dụ: Tính độ dốc tại x = 2
x_value = 2
slope = slope_at_point(x_value)
print(f"Độ dốc của đa thức tại x = {x_value} là {slope}")



Độ dốc của đa thức tại x = 2 là 1159


In [25]:
#BTVN 1:
# Tạo một tensor x có giá trị ban đầu là 2.0
# định nghĩa hàm số và tính gradient
# y = x^3 + 2x^2 + 5x + 1
# Hãy tính dy/dx tại giá trị của x
# Dùng phương pháp gradient Descent với learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lặp

import torch

# Tạo một tensor x có giá trị ban đầu là 2.0
x = torch.tensor(2.0, requires_grad=True)

# Định nghĩa hàm số
def function(x):
    return x**3 + 2*x**2 + 5*x + 1

# Tính giá trị của hàm số tại x = 2.0
y = function(x)

# Tính đạo hàm dy/dx
y.backward()
print(f"Giá trị của dy/dx tại x = 2.0: {x.grad.item()}")

# Số vòng lặp và learning rate
alpha = 0.1
num_iterations = 10

# Đặt lại giá trị của x và gradient
x = torch.tensor(2.0, requires_grad=True)

# Vòng lặp cập nhật x bằng Gradient Descent
for i in range(num_iterations):
    # Tính giá trị của hàm số
    y = function(x)
    
    # Tính gradient
    y.backward()
    
    # In giá trị của dy/dx tại mỗi bước
    print(f"Iteration {i+1}: dy/dx = {x.grad.item()}")
    
    # Cập nhật giá trị của x
    with torch.no_grad():
        x -= alpha * x.grad
    
    # Đặt lại gradient về 0
    x.grad.zero_()
    
    # In kết quả sau mỗi vòng lặp
    print(f"Iteration {i+1}: x = {x.item()}")



Giá trị của dy/dx tại x = 2.0: 25.0
Iteration 1: dy/dx = 25.0
Iteration 1: x = -0.5
Iteration 2: dy/dx = 3.75
Iteration 2: x = -0.875
Iteration 3: dy/dx = 3.796875
Iteration 3: x = -1.2546875476837158
Iteration 4: dy/dx = 4.703972339630127
Iteration 4: x = -1.7250847816467285
Iteration 5: dy/dx = 7.027413368225098
Iteration 5: x = -2.427826166152954
Iteration 6: dy/dx = 12.971714973449707
Iteration 6: x = -3.7249975204467773
Iteration 7: dy/dx = 31.726829528808594
Iteration 7: x = -6.897680282592773
Iteration 8: dy/dx = 120.14325714111328
Iteration 8: x = -18.912006378173828
Iteration 9: dy/dx = 1002.3439331054688
Iteration 9: x = -119.14640808105469
Iteration 10: dy/dx = 42116.01171875
Iteration 10: x = -4330.74755859375


In [26]:
#BTVN 2
# Tạo một tập dữ liệu với x là số giờ học ngẫu nhiên từ 1 đến 10 và y là số điểm được tính theo công thức y = 3x + 5 + noise
# với noise là một giá trị ngẫu nhiên nhỏ
# 1.khởi tạo tham số w và b ngẫu nhiên với requires_gradient = True
# 2. Tính MSE
# 3. TÍnh gradient
# 4. Cập nhật tham số w và b bằng gradient descent với learning rate alpha = 0.01
# 5. Lặp lại quá trình trên trong 100 vòng lặp và quan sat hội tụ của mô hình

import torch
import random

# Tạo tập dữ liệu
num_samples = 100
x = torch.tensor([random.uniform(1, 10) for _ in range(num_samples)], dtype=torch.float32)
x = x.view(-1, 1)  # Chuyển thành tensor cột
noise = torch.tensor([random.uniform(-1, 1) for _ in range(num_samples)], dtype=torch.float32).view(-1, 1)
y = 3 * x + 5 + noise  # y = 3x + 5 + noise

# Khởi tạo tham số w và b
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# Learning rate và số vòng lặp
alpha = 0.01
num_iterations = 100

# Hàm tính MSE
def mse_loss(y_pred, y_true):
    return ((y_pred - y_true) ** 2).mean()

# Quá trình huấn luyện
for i in range(num_iterations):
    # Dự đoán giá trị y
    y_pred = w * x + b
    
    # Tính loss (MSE)
    loss = mse_loss(y_pred, y)
    
    # Tính gradient
    loss.backward()
    
    # Cập nhật tham số bằng gradient descent
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad
    
    # Đặt lại gradient về 0
    w.grad.zero_()
    b.grad.zero_()
    
    # In loss sau mỗi 10 vòng lặp
    if (i + 1) % 10 == 0:
        print(f"Iteration {i+1}: Loss = {loss.item():.4f}, w = {w.item():.4f}, b = {b.item():.4f}")

# In kết quả cuối cùng
print(f"Final parameters: w = {w.item():.4f}, b = {b.item():.4f}")


Iteration 10: Loss = 7.2914, w = 3.8347, b = -0.4341
Iteration 20: Loss = 6.7319, w = 3.7989, b = -0.2010
Iteration 30: Loss = 6.2175, w = 3.7647, b = 0.0224
Iteration 40: Loss = 5.7447, w = 3.7318, b = 0.2367
Iteration 50: Loss = 5.3102, w = 3.7003, b = 0.4421
Iteration 60: Loss = 4.9107, w = 3.6701, b = 0.6390
Iteration 70: Loss = 4.5436, w = 3.6411, b = 0.8278
Iteration 80: Loss = 4.2061, w = 3.6134, b = 1.0088
Iteration 90: Loss = 3.8958, w = 3.5867, b = 1.1823
Iteration 100: Loss = 3.6107, w = 3.5612, b = 1.3487
Final parameters: w = 3.5612, b = 1.3487


In [27]:
# pytorch with tensor
import torch
import numpy as np
torch.__version__

# Chuyển đổi mảng numpy sang tensor pytorch
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

x = torch.from_numpy(arr)
print(x)
print(x.dtype)
print(x.type())

arr2 = np.arange(0.,12.).reshape(4,3)
arr2

x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>
tensor([1, 2, 3, 4, 5])
torch.int64
torch.LongTensor
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [ ]:
# BTVN 3: giải thích lý do tại sao cho 2 trường hợp trên
arr = np.arange(0,5)
x = torch.from_numpy(arr)
print(x)

arr[0] = 99
print(x)

arr = np.arange(0,5)
y = torch.tensor(arr)
print(y)

arr[0] = 99
print(y)

'''torch.from_numpy(arr) tạo tensor chia sẻ bộ nhớ với mảng NumPy, nên khi arr thay đổi, tensor cũng thay đổi.
torch.tensor(arr) tạo một bản sao độc lập, nên thay đổi arr không ảnh hưởng đến tensor.'''

tensor([0, 1, 2, 3, 4])
tensor([99,  1,  2,  3,  4])
tensor([0, 1, 2, 3, 4])
tensor([0, 1, 2, 3, 4])


In [29]:
# BTVN 4: bạn hãy tạo tensor với:
# Empyty
# Zeros
# Ones
# Random
#Reshape với view và view as

import torch

# Tạo tensor rỗng (không khởi tạo giá trị)
empty_tensor = torch.empty(3, 3)
print("Empty Tensor:\n", empty_tensor)

# Tạo tensor toàn số 0
zeros_tensor = torch.zeros(3, 3)
print("\nZeros Tensor:\n", zeros_tensor)

# Tạo tensor toàn số 1
ones_tensor = torch.ones(3, 3)
print("\nOnes Tensor:\n", ones_tensor)

# Tạo tensor với giá trị ngẫu nhiên
random_tensor = torch.rand(3, 3)
print("\nRandom Tensor:\n", random_tensor)

# Reshape tensor bằng view
reshaped_tensor = random_tensor.view(1, 9)
print("\nReshaped Tensor with view:\n", reshaped_tensor)

# Reshape tensor bằng view_as (phải có cùng số phần tử)
example_tensor = torch.zeros(1, 9)
view_as_tensor = random_tensor.view_as(example_tensor)
print("\nReshaped Tensor with view_as:\n", view_as_tensor)


Empty Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Random Tensor:
 tensor([[0.8167, 0.0125, 0.7943],
        [0.7617, 0.8980, 0.2419],
        [0.2522, 0.0574, 0.8276]])

Reshaped Tensor with view:
 tensor([[0.8167, 0.0125, 0.7943, 0.7617, 0.8980, 0.2419, 0.2522, 0.0574, 0.8276]])

Reshaped Tensor with view_as:
 tensor([[0.8167, 0.0125, 0.7943, 0.7617, 0.8980, 0.2419, 0.2522, 0.0574, 0.8276]])
